# External sources dropped by CubeIDE regenerate
# Included from Debug/makefile via ../makefile.targets (not overwritten by Cube).

-include Debug/sensor_drivers/subdir.mk
-include Debug/app_extra/subdir.mk
