#!/usr/bin/env python3
"""Convert an ESP32MT6835Setup serial dump into include/mt6835_restore_map.h.

Usage:
  python dump_to_restore_map.py mt6835_dump_healthy.txt
  python dump_to_restore_map.py mt6835_dump_healthy.txt -o include/mt6835_restore_map.h
"""

from __future__ import print_function

import argparse
import os
import re
import sys

REG_LINE = re.compile(r"^reg,0x([0-9A-Fa-f]+),0x([0-9A-Fa-f]+)\s*$")

# Must match Mt6835::eepromAddrList / kEepromMapLen.
EXPECTED_ADDRS = [0x001] + list(range(0x007, 0x0D3))


def read_text(path):
    raw = open(path, "rb").read()
    if raw.startswith(b"\xff\xfe") or raw.startswith(b"\xfe\xff"):
        return raw.decode("utf-16")
    if raw.startswith(b"\xef\xbb\xbf"):
        return raw.decode("utf-8-sig")
    return raw.decode("utf-8", errors="replace")


def parse_dump(text):
    found = {}
    for line in text.splitlines():
        m = REG_LINE.match(line.strip())
        if not m:
            continue
        addr = int(m.group(1), 16)
        val = int(m.group(2), 16)
        found[addr] = val
    missing = [a for a in EXPECTED_ADDRS if a not in found]
    extra = sorted(a for a in found if a not in EXPECTED_ADDRS)
    if missing or extra:
        raise SystemExit(
            "dump does not match EEPROM map: missing=%s extra=%s"
            % ([hex(a) for a in missing[:8]], [hex(a) for a in extra[:8]])
        )
    return [found[a] for a in EXPECTED_ADDRS]


def render_header(vals, source):
    lines = [
        "#pragma once",
        "",
        "#include <stdint.h>",
        "",
        "/* Generated by dump_to_restore_map.py from %s - do not edit. */" % source,
        "#define MT6835_RESTORE_MAP_COUNT %u" % len(vals),
        "static const uint8_t kRestoreVals[MT6835_RESTORE_MAP_COUNT] = {",
    ]
    row = []
    for i, v in enumerate(vals):
        row.append("0x%02X" % v)
        if len(row) == 16 or i == len(vals) - 1:
            lines.append("    " + ", ".join(row) + ",")
            row = []
    lines.append("};")
    lines.append("")
    return "\n".join(lines) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("dump", help="serial log containing reg,0xADDR,0xVV lines")
    parser.add_argument(
        "-o",
        "--output",
        default=os.path.join(os.path.dirname(os.path.abspath(__file__)),
                             "include", "mt6835_restore_map.h"),
    )
    args = parser.parse_args()
    vals = parse_dump(read_text(args.dump))
    header = render_header(vals, os.path.basename(args.dump))
    os.makedirs(os.path.dirname(args.output) or ".", exist_ok=True)
    with open(args.output, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(header)
    print("wrote %s (%u bytes)" % (args.output, len(vals)))


if __name__ == "__main__":
    main()
